### ISSUE TITLE
Custom projection support

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/vscode-map-preview#16]
Currently the implemented `Map preview (with projection)` command only realistically supports 2 projections:
- EPSG:4326
- EPSG:3857

Anything else and the current preview won't recognize the supplied projection.

For custom projections to work, it means we have to introduce proj4js into the mix.
- [x] Add an configuration section where additional projections can be registered. Direct users (via docs or other means) to grabe proj4js strings from epsg.io
- [x] Inject these additional projections into the preview HTML after proj4js has been bootstrapped and connected to OpenLayers

**Comment by xerosugar** [comment]
Would love to see this implemented! I wish I could get a preview of my map data in EPSG:3006.
