### ISSUE TITLE
local image preview in frame ?

### ISSUE THREAD

**Issue by jonlepage** [jumpinjackie/vscode-map-preview#25]
**Hi friend,** 
I'm desperately looking for a plugin, which will allow me to simply visualize a reference to an image.

I have to build a huge database.
Similar to Json, but in JS.
Do you have an idea if a plugin that would allow me to visualize a local image in a frames exists?

I took the time to make a small image to show my need.
I will be really happy if, through your experience, you will have a small plugin that will allow this feature.
I would like to see a local image when my mouse passes over a link that references a local image.

Preview
http://imgbox.com/sHLBF4kF
![vsc-plugin-iomage-preview](https://cloud.githubusercontent.com/assets/24865815/24588940/d56b66b8-179f-11e7-8fd3-6116607f3f51.jpg)

Do you have an idea if your plugin can do something similar, or know you a plugin that could have this feature?

Thank you very much for your help.

**Comment by jumpinjackie** [comment]
No to both questions. Sorry. Good luck on your search.
