### ISSUE TITLE
Running the contributed command:'map.preview' failed.

### ISSUE THREAD

**Issue by smcardle** [jumpinjackie/vscode-map-preview#28]
Opening a GeoJSON file then selecting map preview causes the following error to display

Running the contributed command:'map.preview' failed.

The GeoJSON file is 103.5 MB and was exported from mapshaper.org

Steve

**Comment by jumpinjackie** [comment]
> The GeoJSON file is 103.5 MB

o_O

I don't think this extension was designed to preview files of that size

**Comment by netotz** [comment]
same problem, my file is 139 MB

**Comment by szewah** [comment]
Same problem. My file is 1.32GB

**Comment by jumpinjackie** [comment]
Sorry, but VSCode's extension APIs will not cooperate with us when working with files over a certain limit (currently 50MB). Such files we cannot get important information about the open document to initiate a map preview.

Until VSCode improves their extension API support around large files, there is nothing I can do here: https://github.com/microsoft/vscode/issues/31078

For the next `0.6.0` release, we will show the error message `This file is too big to be previewed` if attempting to map preview such a large file.
