### ISSUE TITLE
Configurable base layers

### ISSUE THREAD

**Issue by jumpinjackie** [jumpinjackie/vscode-map-preview#3]
Provide a configuration point to allow additional base layers to be added to the preview map

**Comment by huanglii** [comment]
Can I customize the baselayer, such as WMTS url?

**Comment by jumpinjackie** [comment]
Not yet

**Comment by gdinatale91** [comment]
I couldn't find in the source code where the 4 base maps are being loaded, is there a way we can at least hardcode a new map, even if it means building the extension ourselves?
