### ISSUE TITLE
I Want to updata this project, but i can't run it

### ISSUE THREAD

**Issue by CandyACE** [jumpinjackie/vscode-map-preview#30]
I Want to updata this project, but i can't run it.

**Comment by jumpinjackie** [comment]
1. Clone this repo
2. In the clone `npm install` or `yarn install` to install required dependencies
3. Open the clone folder in vscode and hit F5 to start debugging, that will launch vscode as an extension host with this extension loaded.

I haven't touched this code in over 2 years, but the instructions are still the same as they were 2 years ago.

**Comment by CandyACE** [comment]
think you , i will try

**Comment by CandyACE** [comment]
![image](https://user-images.githubusercontent.com/31685984/50216296-55d2e700-03c0-11e9-97bc-afa1e7ff839d.png)
I aways have some error, it can't get some module.
