### ISSUE TITLE
Configurable line/polygon vertices display

### ISSUE THREAD

**Issue by sikmir** [jumpinjackie/vscode-map-preview#33]
That is really useful feature I miss now.

Just as quick prototype, I've modified the style a bit:
https://github.com/jumpinjackie/vscode-map-preview/blob/e5d36f4484791991dce9d9f768f52b60afab6322/static/preview.js#L126-L131

```javascript
    var lineStyle = [
        new ol.style.Style({
            fill: new ol.style.Stroke({
                color: previewSettings.style.line.stroke.color
            }),
            stroke: new ol.style.Stroke(previewSettings.style.line.stroke)
        }),
        new ol.style.Style({
            image: new ol.style.Circle({
                radius: 3,
                fill: new ol.style.Fill({
                    color: 'black'
                })
            }),
            geometry: function(feature) {
                return new ol.geom.MultiPoint(feature.getGeometry().getCoordinates()[0]);
            }
        })
    ];
```
Result:
![scr1](https://user-images.githubusercontent.com/688044/54379625-d0975f80-469a-11e9-8a91-e7526734364d.jpg)

**Comment by sikmir** [comment]
I've tested with GPX track with multiple segments, and nodes displayed only for the first segment.
Looks like something wrong here:
https://github.com/jumpinjackie/vscode-map-preview/blob/74d2308d33e41c38ee8a59194a5f3a788cc07e40/static/preview.js#L130
But just removing `[0]` doesn't help either.

**Comment by jumpinjackie** [comment]
Could you attach or point me to a GPX file that demonstrates the problem?

**Comment by sikmir** [comment]
Here is GPX file example: [New track.gpx.txt](https://github.com/jumpinjackie/vscode-map-preview/files/2981812/New.track.gpx.txt)

And result:
![scr1](https://user-images.githubusercontent.com/688044/54584144-9249c980-4a27-11e9-84c0-ef0c8576961e.jpg)

**Comment by jumpinjackie** [comment]
Should be fixed properly now (wasn't handling properly for all geometry types)
