### ISSUE TITLE
GeoJSON GeometryCollection not working / missing

### ISSUE THREAD

**Issue by meschg** [jumpinjackie/vscode-map-preview#34]
Hello, 

in my tests in looks like the GeometryCollection with the example is not rendering at all. The problem also appears in combination features collection

Best wishes
Gerhard

Specification:
https://tools.ietf.org/html/rfc7946#appendix-A.7

Minimal JSON Test code:
```
{
    "type": "GeometryCollection",
    "geometries": [
        {
            "type": "LineString",
            "coordinates": [
                [
                    101.0,
                    0.0
                ],
                [
                    102.0,
                    10.0
                ]
            ]
        }
    ]
}
```

Expected Result (Without Colleciton):
![2019-03-16 13_14_05-Map Preview_ polygon json - Worldtrix-Alpha - Visual Studio Code](https://user-images.githubusercontent.com/5106318/54475090-ad30f980-47ed-11e9-941b-759eb53c8017.png)

Geometrie & Features collection test file:
[geometrie_feature_collection.txt](https://github.com/jumpinjackie/vscode-map-preview/files/2973891/geometrie_feature_collection.txt)

**Comment by meschg** [comment]
Thanks for the fast fix.

**Comment by ben-src** [comment]
I'm still getting this problem with it not showing a FeatureCollection containing a GeometryCollection
