### ISSUE TITLE
backslashes in geojson properties cause parsing to fail

### ISSUE THREAD

**Issue by mikepianka** [jumpinjackie/vscode-map-preview#37]
If there are backslashes in a geojson feature's properties, such as a linked filepath, it will cause parsing to fail. Escaping the backslash does not fix the issue either.

Causes Error:
{
  "type" : "FeatureCollection",
  "features" : [
    {
      "type" : "Feature",
      "id" : 570,
      "geometry" : {
        "type" : "Point",
        "coordinates" : [
          -73.828791392048288,
          42.675982296298386,
          22.675982296298386
        ]
      },
      "properties" : {
        "OBJECTID" : 570,
        "Image_Number" : 1332,
        "Image_Path" : "q:/maindir/subdir\\photo_1332.jpg"
      }
    }
  ]
}

Works:
{
  "type" : "FeatureCollection",
  "features" : [
    {
      "type" : "Feature",
      "id" : 570,
      "geometry" : {
        "type" : "Point",
        "coordinates" : [
          -73.828791392048288,
          42.675982296298386,
          22.675982296298386
        ]
      },
      "properties" : {
        "OBJECTID" : 570,
        "Image_Number" : 1332,
        "Image_Path" : "q:/maindir/subdir/photo_1332.jpg"
      }
    }
  ]
}

**Comment by jumpinjackie** [comment]
I'm on the fence about the extension attempting to fix bad data when switching to JSON language mode in VSCode already tells you about this problem.

![already_bad_json](https://user-images.githubusercontent.com/563860/66093098-2a795b80-e5d2-11e9-916f-17901ae3d8ee.png)

**Comment by mikepianka** [comment]
Escaping the backslash with a '\\\' is valid json but does still cause the map preview to fail though. 

So "q:/maindir/subdir\\\photo_1332.jpg" would fail.

**Comment by jumpinjackie** [comment]
Ok I see what you're getting at
