### ISSUE TITLE
Porjection incorrect in EPSG:32735

### ISSUE THREAD

**Issue by tigerbook73** [jumpinjackie/vscode-map-preview#38]
In EPSG:32735 WGS 84 / UTM zone 35S:
(x, y) : (415000, 6450000) (in South Africa) shall be transformed to (long, lat): (26°5'57.505", -32°4'59.107").

While in map-view, it is transformed to around (long, lat): (57.9413, 3.7245).

**Comment by jumpinjackie** [comment]
Until #16 is implemented, we expect data to be in either `EPSG:4326` or `EPSG:3857`

**Comment by jumpinjackie** [comment]
When I release 0.5.0 (the next version of this extension), there will be a new property `map.preview.projections` where you can register the proj4js definiiton of [EPSG:32735](https://epsg.io/32735) like so:

```
"map.preview.projections": [
        { "epsgCode": 32735, "definition": "+proj=utm +zone=35 +south +datum=WGS84 +units=m +no_defs" }
    ]
```

Then previewing your file using the `Map Preview (with projection)` command should show your data in the correct place with coordinates projected correctly.
