### ISSUE TITLE
Maybe a stupid question but should this handle KML Style IconStyle Icon attributes?

### ISSUE THREAD

**Issue by sjmcdowall** [jumpinjackie/vscode-map-preview#52]
I am trying like heck to change the marker icon -- and nothing I am doing seems to make any difference -- it always show the Yellow Pin thing.  Is this supposed to work? 

Here is the KML I am trying... 
`<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>KmlFile</name>
    <Style id="west_campus_style">
      <IconStyle>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/red-stars.png
          </href>
        </Icon>
      </IconStyle>
      <BalloonStyle>
        <text>$[video]</text>
      </BalloonStyle>
    </Style>
    <Placemark>
      <name>Google West Campus 1</name>
      <styleUrl>#west_campus_style</styleUrl>
      <ExtendedData>
        <Data name="video">
          <value><![CDATA[<iframe width="480" height="360"
            src="https://www.youtube.com/embed/ZE8ODPL2VPI" frameborder="0"
            allowfullscreen></iframe><br><br>]]></value>
        </Data>
      </ExtendedData>
      <Point>
        <coordinates>-122.0914977709329,37.42390182131783,0</coordinates>
      </Point>
    </Placemark>
    <Placemark>
      <name>Google West Campus 2</name>
      <styleUrl>#west_campus_style</styleUrl>
      <ExtendedData>
        <Data name="video">
          <value><![CDATA[<iframe width="480" height="360"
            src="https://www.youtube.com/embed/nb4gvrNrDWw" frameborder="0"
            allowfullscreen></iframe><br><br>]]></value>
        </Data>
      </ExtendedData>
      <Point>
        <coordinates>-122.0926995893311,37.42419403634421,0</coordinates>
      </Point>
    </Placemark>
    <Placemark>
      <name>Google West Campus 3</name>
      <styleUrl>#west_campus_style</styleUrl>
      <ExtendedData>
        <Data name="video">
          <value><![CDATA[<iframe width="480" height="360"
            src="https://www.youtube.com/embed/0hhiEjf7_NA" frameborder="0"
            allowfullscreen></iframe><br><br>]]></value>
        </Data>
      </ExtendedData>
      <Point>
        <coordinates>-122.0922532985281,37.42301710721216,0</coordinates>
      </Point>
    </Placemark>
  </Document>
</kml>
`

**Comment by jumpinjackie** [comment]
Fixed in 0.5.7.

NOTE: Due to content security restrictions on the webview, you must use `https` for KML icon urls, otherwise the icons will not render.
