### ISSUE TITLE
KML lines disappearing after zooming

### ISSUE THREAD

**Issue by tyanderson91** [jumpinjackie/vscode-map-preview#53]
I have a kml with some lines/curves that span the whole globe, including crossing the international date line and the prime meridian. These show up when zoomed all the way out. However, when zooming in even just a little bit, they disappear and don't come back until I zoom back out. I should be able to view portions of a line from .kml when zooming in.

**Comment by jumpinjackie** [comment]
Are you able to provide an example KML file that demonstrates the problem?

**Comment by tyanderson91** [comment]
Can't attach a file but here is an example:
```<?xml version="1.0" encoding="UTF-8"?>
<kml>
    <Document id="19">
        <Style id="22">
            <LineStyle id="23">
                <color>ff0000ff</color>
                <colorMode>normal</colorMode>
                <width>2</width>
            </LineStyle>
        </Style>
        <Placemark id="25">
            <name>Some Line</name>
            <styleUrl>#23</styleUrl>
            <LineString id="24">
                <coordinates>280,20,0 250,0,0 220,-20,0 150,-35,0 100,-50,0 100,-65,0 70,-80,0 50,-70,0 30,-45,0 15,-5,0 5,20,0</coordinates>
                <altitudeMode>clampToGround</altitudeMode>
            </LineString>
        </Placemark>
    </Document>
</kml>
```
It looks like the problem only occurs when trying to zoom in/pan to North America through the middle of the Pacific Ocean; Australia through Africa work fine. In fact, the disappearing seems to happen right at the east edge of the international date line and through the rest of the western hemisphere. Maybe it's related to the longitude values being on a 0 to 360 scale instead of -180 to 180?
