### ISSUE TITLE
Support other CRS 

### ISSUE THREAD

**Issue by Jeongyong-park** [jumpinjackie/vscode-map-preview#55]
I hope to support other coordinate reference systems other than EPSG: 4326 and EPSG: 3857.

like a  below geojson file.

``` json
{
"type": "FeatureCollection",
"name": "test",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::5186" } },
"features": [
{ "type": "Feature", "id": "0", "properties": { "name": "BH-1", "easting": 197992.417, "northing": 534960.622, "ground_altitude": 50.17, "thick_1": 0.8, "thick_2": 1.2, "thick_3": 6.0, "thick_4": 22.0, "thick_5": 0, "thick_6": 0, "thick_1_high": 50.17, "thick_1_low": 49.37, "thick_2_high": 49.37, "thick_2_low": 48.17, "thick_3_high": 48.17, "thick_3_low": 42.17, "thick_4_high": 42.17, "thick_4_low": 20.17, "thick_5_high": 20.17, "thick_5_low": 20.17, "thick_6_high": 20.17, "thick_6_low": 20.17, "type": "Borehole" }, "geometry": { "type": "Point", "coordinates": [ 197992.416999999986729, 534960.621999999973923 ] } },
]
}
```

**Comment by jumpinjackie** [comment]
You need to edit your VSCode configuration and edit the [map.preview.projections](https://github.com/jumpinjackie/vscode-map-preview/blob/master/CONFIGURATION.md#mappreviewprojections-new-in-050) setting to include the [proj4js definition of EPSG:5186](http://epsg.io/5186)

Once that is done (and you delete the trailing comma after your first feature in your example GeoJSON), the file can be previewed.

![2021-05-20 19_40_49-Map Preview_ 5186 geojson - Untitled (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/563860/118956893-5c0b8a00-b9a3-11eb-950b-c8248dd3fe6a.png)
