### ISSUE TITLE
Possibility of compatibility with postgis tables?

### ISSUE THREAD

**Issue by aferrar** [jumpinjackie/vscode-map-preview#57]
Greetings,

Thanks for providing this awesome extension. Was wondering if there was any possibility of including the ability to visualize spatially enabled postgresql connected tables?

Thanks again!

**Comment by jumpinjackie** [comment]
Not likely, we use OpenLayers as the engine for map/spatial data visualization. If it can't consume postgis tables directly, neither can this extension. PostGIS tables generally are fronted by some dedicated GIS server software (eg. GeoServer) that would expose postgis tables as WFS / WMS layers.

Also postgis tables are somewhat outside the scope of what this extension is trying to accomplish: A *text editor* extension to easily preview *plain-text* snippets of geographic data. At this stage, you're venturing into territory best served by dedicated GIS software/tools.

**Comment by aferrar** [comment]
Understandable, I appreciate you taking the time to respond and explain. Thanks again for the awesome extension!
