### ISSUE TITLE
set centre point and zoom level

### ISSUE THREAD

**Issue by wi-fr** [jumpinjackie/vscode-map-preview#58]
On rendering a map, the initial zoom level is determined by the areal distribution of the features to be shown. Is there a way to set the centre point and the zoom level explicitly?

**Comment by jumpinjackie** [comment]
Sorry, that is not possible.

Also IMO it isn't really practical for previewing. You want to *see* your data the moment the map renders right? Initial view based on "best fit" of the data being previewed is the way to achieve that.
